-- Every prompt sent to Claude Code (from history.jsonl)
CREATE TABLE IF NOT EXISTS claude_prompts (
    id           INTEGER PRIMARY KEY,
    session_id   TEXT NOT NULL,
    ts           INTEGER NOT NULL,  -- epoch ms
    project      TEXT,
    cwd          TEXT,
    prompt_text  TEXT
);

-- Full message turns from transcript jsonl files
CREATE TABLE IF NOT EXISTS claude_messages (
    id           INTEGER PRIMARY KEY,
    uuid         TEXT UNIQUE,
    session_id   TEXT NOT NULL,
    ts           TEXT,              -- ISO timestamp
    role         TEXT,             -- 'user' or 'assistant'
    content_text TEXT,
    tool_name    TEXT,             -- set if role=assistant and it's a tool_use block
    project      TEXT,
    cwd          TEXT,
    source_file  TEXT              -- which .jsonl this came from
);

-- Claude Code sessions (from sessions/*.json)
CREATE TABLE IF NOT EXISTS claude_sessions (
    session_id   TEXT PRIMARY KEY,
    pid          INTEGER,
    cwd          TEXT,
    project      TEXT,
    started_at   INTEGER,          -- epoch ms
    updated_at   INTEGER,
    status       TEXT,             -- 'active', 'idle', 'ended'
    version      TEXT,
    kind         TEXT
);

-- FTS index over messages for fast search
CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
    content_text,
    role,
    project,
    cwd,
    ts,
    uuid,
    session_id,
    content='claude_messages',
    content_rowid='id'
);

-- FTS index over prompts
CREATE VIRTUAL TABLE IF NOT EXISTS prompts_fts USING fts5(
    prompt_text,
    project,
    cwd,
    session_id,
    content='claude_prompts',
    content_rowid='id'
);

-- Semantic embeddings (one row per indexed message)
CREATE TABLE IF NOT EXISTS message_embeddings (
    message_id  INTEGER PRIMARY KEY REFERENCES claude_messages(id),
    embedding   BLOB NOT NULL,   -- float32 numpy array, L2-normalized
    model       TEXT             -- model name that generated this
);

-- Cached narrative summaries per session (generated by Ollama)
CREATE TABLE IF NOT EXISTS session_summaries (
    session_id   TEXT PRIMARY KEY,
    summary      TEXT,
    highlights   TEXT,   -- JSON list of key moments
    generated_at INTEGER,
    model        TEXT
);

-- Pinned sessions
CREATE TABLE IF NOT EXISTS session_pins (
    session_id  TEXT PRIMARY KEY,
    pinned_at   INTEGER NOT NULL
);

-- Per-session user notes
CREATE TABLE IF NOT EXISTS session_notes (
    session_id  TEXT PRIMARY KEY,
    note        TEXT NOT NULL,
    updated_at  INTEGER NOT NULL
);

-- Session view history (for "recently viewed")
CREATE TABLE IF NOT EXISTS session_views (
    id          INTEGER PRIMARY KEY,
    session_id  TEXT NOT NULL,
    viewed_at   INTEGER NOT NULL
);

-- Generated titles and summaries per session (cached, computed once)
CREATE TABLE IF NOT EXISTS session_titles (
    session_id   TEXT PRIMARY KEY,
    title        TEXT,              -- 6-8 word clean title
    summary      TEXT,              -- 1-2 sentence summary
    project_tags TEXT,              -- comma-separated detected project tags
    generated_at INTEGER,
    method       TEXT               -- 'heuristic' or 'ollama'
);

-- Sync state: track which files have been indexed and when
CREATE TABLE IF NOT EXISTS sync_state (
    file_path    TEXT PRIMARY KEY,
    last_size    INTEGER,
    last_mtime   REAL,
    indexed_at   INTEGER
);

-- Session links — groups related or continuation sessions together
CREATE TABLE IF NOT EXISTS session_links (
    id          INTEGER PRIMARY KEY,
    session_id  TEXT NOT NULL,   -- this session
    linked_to   TEXT NOT NULL,   -- is linked to this session
    link_type   TEXT DEFAULT 'continuation',  -- 'continuation' | 'related' | 'split'
    note        TEXT,            -- optional note about the link
    created_at  INTEGER NOT NULL,
    UNIQUE(session_id, linked_to)
);

-- Shell command log (populated by daemon/shell_hook.sh)
CREATE TABLE IF NOT EXISTS shell_commands (
    id          INTEGER PRIMARY KEY,
    ts          INTEGER NOT NULL,     -- command start time, epoch ms
    duration_ms INTEGER,              -- how long it ran in ms
    exit_code   INTEGER,              -- exit status (0 = success)
    command     TEXT NOT NULL,        -- full command text as typed
    cwd         TEXT,                 -- working directory when command ran
    shell_pid   INTEGER               -- shell PID — groups commands in one terminal session
);

CREATE UNIQUE INDEX IF NOT EXISTS shell_commands_unique
    ON shell_commands(ts, command);

-- FTS index over shell commands
CREATE VIRTUAL TABLE IF NOT EXISTS shell_commands_fts USING fts5(
    command,
    cwd,
    content='shell_commands',
    content_rowid='id'
);
